### ISSUE TITLE
Select ESP list remains empty

### ISSUE THREAD

**Issue by consolacion** [ErfanDL/ESPOTADASH_Library#1]
Great project, but uploading  does not work (for me that is), as I can't select an ESP...the select ESP list remains empty. I have only two devices registered, 
Not sure if important, but after upload of the basic example software through the IDE, I get an "Invalid library found in /home/user/Arduino/libraries/ESP32OTAUpdater: Missing 'version' from library" message. But the software registers fine (judging from the serial output and as the webserver says they are registered)
Also: I have changed the index.js file to use port 3600, rather than 3000.

**Comment by ErfanDL** [comment]
Hi, by refreshing the page list will be appear.

**Comment by consolacion** [comment]
Correct. Tnx
Again. Great Software
