### ISSUE TITLE
ESP32 build ERROR

### ISSUE THREAD

**Issue by legaxus** [ErfanDL/ESPOTADASH_Library#2]
Appreciate if you could help to solve the error. Thanks.

C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp: In member function 'void ESPOTADASH::loop()':
C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:83:37: error: 'ESP32shttpUpdate' was not declared in this scope
           t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here
                                     ^~~~~~~~~~~~~~~~
C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:83:37: note: suggested alternative: 'ESPhttpUpdate'
           t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here
                                     ^~~~~~~~~~~~~~~~
                                     ESPhttpUpdate

**Comment by ErfanDL** [comment]
> Appreciate if you could help to solve the error. Thanks.
> 
> C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp: In member function 'void ESPOTADASH::loop()': C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:83:37: error: 'ESP32shttpUpdate' was not declared in this scope t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here ^~~~~~~~~~~~~~~~ C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:83:37: note: suggested alternative: 'ESPhttpUpdate' t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here ^~~~~~~~~~~~~~~~ ESPhttpUpdate

Hi, Make sure you have the latest version of the ESP32 board package installed in the Arduino IDE also please update the ESPOTADASH library to latest.

**Comment by legaxus** [comment]
> > Appreciate if you could help to solve the error. Thanks.
> > C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp: In member function 'void ESPOTADASH::loop()': C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:83:37: error: 'ESP32shttpUpdate' was not declared in this scope t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here ^~~~~~~~~~~~~~~~ C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:83:37: note: suggested alternative: 'ESPhttpUpdate' t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here ^~~~~~~~~~~~~~~~ ESPhttpUpdate
> 
> Hi, Make sure you have the latest version of the ESP32 and ESP8266 board package installed in the Arduino IDE also please update the ESPOTADASH library to latest.

After updated ESP32 and ESP8266 board package. Also update with latest ESPOTADASH, 

C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp: In member function 'void ESPOTADASH::loop()':
C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:104:39: error: 'ESP32shttpUpdate' was not declared in this scope
             t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here
                                       ^~~~~~~~~~~~~~~~
C:\Users\LEGAXUS\Downloads\arduino1819\portable\sketchbook\libraries\ESPOTADASH\ESPOTADASH.cpp:104:39: note: suggested alternative: 'ESPhttpUpdate'
             t_httpUpdate_return ret = ESP32shttpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here
                                       ^~~~~~~~~~~~~~~~
                                       ESPhttpUpdate

**Comment by legaxus** [comment]
Attached with photos
![otadasherror1](https://github.com/ErfanDL/ESPOTADASH_Library/assets/122014240/f82bdb99-4007-4e7b-9c47-f32f816de274)
![otadasherror2](https://github.com/ErfanDL/ESPOTADASH_Library/assets/122014240/7687fcd8-92a3-4a4f-856c-c36ec0582ace)
![otadasherror3](https://github.com/ErfanDL/ESPOTADASH_Library/assets/122014240/4ba9ba86-81ec-4b68-95f1-de62c120c732)

**Comment by ErfanDL** [comment]
> 

This error says that the ESP32OTAUpdater library was not found. please copy the ESP32OTAUpdater to root of your libraries folder.

**Comment by ErfanDL** [comment]
> Attached with photos 

This error says that the ESP32OTAUpdater library was not found. please copy the ESP32OTAUpdater to root of your libraries folder.

**Comment by legaxus** [comment]
the meaning of root of libraries folder is same libraries as ESPOTADASH library? attached the photo of current library location
![otadasherror4](https://github.com/ErfanDL/ESPOTADASH_Library/assets/122014240/c988b346-7e24-4eeb-863d-7d09997c2e5e)

**Comment by ErfanDL** [comment]
Yes, I think the problem is with the portable version. The libraries must be in the path of the  \Documents\Arduino\libraries

**Comment by ErfanDL** [comment]
> the meaning of root of libraries folder is same libraries as ESPOTADASH library? attached the photo of current library location 
Yes, I think the problem is with the portable version. The libraries must be in the path of the \Documents\Arduino\libraries

**Comment by legaxus** [comment]
Anyway we can point the path for portable version? Need some guidance, then I will try, thanks.

**Comment by ErfanDL** [comment]
> Anyway we can point the path for portable version? Need some guidance, then I will try, thanks.

I have never used the portable version. you can ask it from Arduino forum.

**Comment by legaxus** [comment]
ok thanks
